/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IChainlinkAggregatorInterface extends ethers.utils.Interface {
  functions: {
    "requestCryptoPriceERC20(address,address,address,address,uint128,uint96,uint256[],uint256)": FunctionFragment;
    "requestCryptoPriceETH(address,address,address,uint128,uint96,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "requestCryptoPriceERC20",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestCryptoPriceETH",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestCryptoPriceERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestCryptoPriceETH",
    data: BytesLike
  ): Result;

  events: {};
}

export class IChainlinkAggregator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IChainlinkAggregatorInterface;

  functions: {
    requestCryptoPriceERC20(
      _pair: string,
      _token: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      _initialTokenBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestCryptoPriceETH(
      _pair: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  requestCryptoPriceERC20(
    _pair: string,
    _token: string,
    _nft: string,
    _assetRecipient: string,
    _delta: BigNumberish,
    _fee: BigNumberish,
    _initialNFTIDs: BigNumberish[],
    _initialTokenBalance: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestCryptoPriceETH(
    _pair: string,
    _nft: string,
    _assetRecipient: string,
    _delta: BigNumberish,
    _fee: BigNumberish,
    _initialNFTIDs: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    requestCryptoPriceERC20(
      _pair: string,
      _token: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      _initialTokenBalance: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    requestCryptoPriceETH(
      _pair: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    requestCryptoPriceERC20(
      _pair: string,
      _token: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      _initialTokenBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestCryptoPriceETH(
      _pair: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    requestCryptoPriceERC20(
      _pair: string,
      _token: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      _initialTokenBalance: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestCryptoPriceETH(
      _pair: string,
      _nft: string,
      _assetRecipient: string,
      _delta: BigNumberish,
      _fee: BigNumberish,
      _initialNFTIDs: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
