/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface LinearCurveInterface extends ethers.utils.Interface {
  functions: {
    "getBuyInfo(uint128,uint128,uint256,uint256,uint256)": FunctionFragment;
    "getSellInfo(uint128,uint128,uint256,uint256,uint256)": FunctionFragment;
    "validateDelta(uint128)": FunctionFragment;
    "validateSpotPrice(uint128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getBuyInfo",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellInfo",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateDelta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "validateSpotPrice",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getBuyInfo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateDelta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateSpotPrice",
    data: BytesLike
  ): Result;

  events: {};
}

export class LinearCurve extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: LinearCurveInterface;

  functions: {
    getBuyInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
        error: number;
        newSpotPrice: BigNumber;
        newDelta: BigNumber;
        inputValue: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    getSellInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
        error: number;
        newSpotPrice: BigNumber;
        newDelta: BigNumber;
        outputValue: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    validateDelta(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean] & { valid: boolean }>;

    validateSpotPrice(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getBuyInfo(
    spotPrice: BigNumberish,
    delta: BigNumberish,
    numItems: BigNumberish,
    feeMultiplier: BigNumberish,
    protocolFeeMultiplier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
      error: number;
      newSpotPrice: BigNumber;
      newDelta: BigNumber;
      inputValue: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  getSellInfo(
    spotPrice: BigNumberish,
    delta: BigNumberish,
    numItems: BigNumberish,
    feeMultiplier: BigNumberish,
    protocolFeeMultiplier: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
      error: number;
      newSpotPrice: BigNumber;
      newDelta: BigNumber;
      outputValue: BigNumber;
      protocolFee: BigNumber;
    }
  >;

  validateDelta(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  validateSpotPrice(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getBuyInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
        error: number;
        newSpotPrice: BigNumber;
        newDelta: BigNumber;
        inputValue: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    getSellInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber, BigNumber, BigNumber] & {
        error: number;
        newSpotPrice: BigNumber;
        newDelta: BigNumber;
        outputValue: BigNumber;
        protocolFee: BigNumber;
      }
    >;

    validateDelta(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    validateSpotPrice(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getBuyInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSellInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateDelta(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    validateSpotPrice(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getBuyInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSellInfo(
      spotPrice: BigNumberish,
      delta: BigNumberish,
      numItems: BigNumberish,
      feeMultiplier: BigNumberish,
      protocolFeeMultiplier: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateDelta(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    validateSpotPrice(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
