/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IChainlinkAggregator,
  IChainlinkAggregatorInterface,
} from "../IChainlinkAggregator";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract ISeacowsPairERC20",
        name: "_pair",
        type: "address",
      },
      {
        internalType: "contract ERC20",
        name: "_token",
        type: "address",
      },
      {
        internalType: "contract IERC721",
        name: "_nft",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "_assetRecipient",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "_delta",
        type: "uint128",
      },
      {
        internalType: "uint96",
        name: "_fee",
        type: "uint96",
      },
      {
        internalType: "uint256[]",
        name: "_initialNFTIDs",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "_initialTokenBalance",
        type: "uint256",
      },
    ],
    name: "requestCryptoPriceERC20",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ISeacowsPairETH",
        name: "_pair",
        type: "address",
      },
      {
        internalType: "contract IERC721",
        name: "_nft",
        type: "address",
      },
      {
        internalType: "address payable",
        name: "_assetRecipient",
        type: "address",
      },
      {
        internalType: "uint128",
        name: "_delta",
        type: "uint128",
      },
      {
        internalType: "uint96",
        name: "_fee",
        type: "uint96",
      },
      {
        internalType: "uint256[]",
        name: "_initialNFTIDs",
        type: "uint256[]",
      },
    ],
    name: "requestCryptoPriceETH",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IChainlinkAggregator__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkAggregatorInterface {
    return new utils.Interface(_abi) as IChainlinkAggregatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkAggregator {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainlinkAggregator;
  }
}
