/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  OwnableWithTransferCallback,
  OwnableWithTransferCallbackInterface,
} from "../OwnableWithTransferCallback";

const _abi = [
  {
    inputs: [],
    name: "Ownable_NewOwnerZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "Ownable_NotOwner",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class OwnableWithTransferCallback__factory {
  static readonly abi = _abi;
  static createInterface(): OwnableWithTransferCallbackInterface {
    return new utils.Interface(_abi) as OwnableWithTransferCallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OwnableWithTransferCallback {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as OwnableWithTransferCallback;
  }
}
